"""
Self-healing test generator — calls LLM to produce updated pytest code.

Supports:
  - Groq (cloud, BYOK) via GROQ_API_KEY env var
  - Ollama (local, free) via OLLAMA_BASE_URL env var

Usage:
    healer = TestHealer()
    code = healer.generate_tests(drift_report, existing_tests_code, new_schema)
"""
from sentinel.models import DriftReport
from sentinel.config import settings


SYSTEM_PROMPT = """You are an expert Python test engineer specialising in JSON schema validation.
Your job is to update pytest test functions when a JSON schema has drifted.
You will receive:
1. A drift report describing what changed (fields added, removed, type changes)
2. The existing pytest test code
3. The new schema

Rules:
- Output ONLY valid Python code. No explanation, no markdown fences, no preamble.
- Keep all existing tests that are still valid for the new schema
- Add new test functions for newly added fields (test field presence, type, and a happy-path assertion)
- Remove or update test assertions that reference removed fields
- Update type assertions where field types have changed
- Every test function must start with 'test_'
- Use pytest assert statements only — no unittest
- Import jsonschema at the top if not already imported
- Include a module docstring explaining this file was auto-generated by schema-sentinel
"""


def _build_prompt(drift_report: DriftReport, existing_code: str, new_schema: dict) -> str:
    drifts_text = "\n".join(
        f"  - {d.drift_type.value}: {d.field_path} "
        f"(was: {d.old_value}, now: {d.new_value}, severity: {d.severity})"
        for d in drift_report.drifts
    )
    return f"""Schema drift detected for: {drift_report.schema_name}

DRIFT SUMMARY:
{drift_report.summary}

FIELD-LEVEL CHANGES:
{drifts_text}

EXISTING TEST CODE:
```python
{existing_code}
```

NEW SCHEMA (JSON):
{new_schema}

Generate the updated pytest test file now:"""


class TestHealer:

    def __init__(self):
        self.backend = settings.llm_backend.lower()

    def generate_tests(
        self,
        drift_report: DriftReport,
        existing_code: str,
        new_schema: dict,
    ) -> str:
        """
        Call the configured LLM backend and return updated pytest code as a string.
        Raises RuntimeError if the backend is not configured.
        """
        prompt = _build_prompt(drift_report, existing_code, new_schema)

        if self.backend == "groq":
            return self._call_groq(prompt)
        elif self.backend == "ollama":
            return self._call_ollama(prompt)
        else:
            raise RuntimeError(f"Unknown LLM backend: {self.backend}. Set LLM_BACKEND=groq or ollama in .env")

    def _call_groq(self, prompt: str) -> str:
        if not settings.groq_api_key:
            raise RuntimeError("GROQ_API_KEY not set in .env")
        from groq import Groq
        client = Groq(api_key=settings.groq_api_key)
        response = client.chat.completions.create(
            model=settings.groq_model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=4096,
        )
        return response.choices[0].message.content.strip()

    def _call_ollama(self, prompt: str) -> str:
        import ollama
        response = ollama.chat(
            model=settings.ollama_model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            options={"temperature": 0.2},
        )
        return response["message"]["content"].strip()
