"""
Test writer — writes generated test code to local files or creates a GitHub PR.

Local mode:  writes to generated_tests/{schema_name}_tests.py
PR mode:     creates a branch, commits the file, opens a PR, returns PR URL

Controlled by OUTPUT_MODE in .env ("local" or "pr").
"""
from pathlib import Path
from datetime import datetime
from sentinel.config import settings
from sentinel.models import DriftReport


class TestWriter:

    def __init__(self):
        self.output_dir = Path(settings.generated_tests_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write(self, schema_name: str, code: str, drift_report: DriftReport) -> dict:
        """
        Write generated test code.
        Returns dict with keys: mode, path, pr_url (empty string if local mode).
        """
        if settings.output_mode == "pr":
            return self._write_pr(schema_name, code, drift_report)
        else:
            return self._write_local(schema_name, code)

    def _write_local(self, schema_name: str, code: str) -> dict:
        filename = f"test_{schema_name}_generated.py"
        path = self.output_dir / filename
        path.write_text(code)
        return {"mode": "local", "path": str(path), "pr_url": ""}

    def _write_pr(self, schema_name: str, code: str, drift_report: DriftReport) -> dict:
        """
        Create a GitHub branch, commit the test file, and open a PR.
        Requires GITHUB_TOKEN and GITHUB_REPO in .env.
        """
        if not settings.github_token or not settings.github_repo:
            raise RuntimeError("GITHUB_TOKEN and GITHUB_REPO must be set in .env for PR mode")

        from github import Github
        gh = Github(settings.github_token)
        repo = gh.get_repo(settings.github_repo)

        branch_name = f"sentinel/heal-{schema_name}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
        base_ref = repo.get_branch(settings.github_base_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_ref.commit.sha)

        file_path = f"generated_tests/test_{schema_name}_generated.py"
        try:
            existing = repo.get_contents(file_path, ref=settings.github_base_branch)
            repo.update_file(
                path=file_path,
                message=f"sentinel: heal tests for {schema_name} ({drift_report.summary})",
                content=code,
                sha=existing.sha,
                branch=branch_name,
            )
        except Exception:
            repo.create_file(
                path=file_path,
                message=f"sentinel: generate tests for {schema_name} ({drift_report.summary})",
                content=code,
                branch=branch_name,
            )

        pr = repo.create_pull(
            title=f"[schema-sentinel] Heal tests for {schema_name}",
            body=self._pr_body(drift_report),
            head=branch_name,
            base=settings.github_base_branch,
        )
        return {"mode": "pr", "path": file_path, "pr_url": pr.html_url}

    def _pr_body(self, drift_report: DriftReport) -> str:
        lines = [
            "## Schema drift detected by schema-sentinel",
            f"",
            f"**Schema:** `{drift_report.schema_name}`  ",
            f"**Baseline version:** `{drift_report.baseline_version}`  ",
            f"**Detected at:** {drift_report.detected_at.isoformat()}  ",
            f"",
            f"### Summary",
            f"{drift_report.summary}",
            f"",
            f"### Field changes",
        ]
        for d in drift_report.drifts:
            severity_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(d.severity, "⚪")
            lines.append(
                f"- {severity_emoji} `{d.field_path}` — **{d.drift_type.value}** "
                f"(was `{d.old_value}`, now `{d.new_value}`)"
            )
        lines += [
            "",
            "---",
            "_Auto-generated by [schema-sentinel](https://github.com/your-handle/schema-sentinel). Review and merge if the changes look correct._",
        ]
        return "\n".join(lines)
